package com.nike.gbipuidev.perf.test;

import io.gatling.core.Predef._;
import io.gatling.http.Predef._;
import io.gatling.http.HeaderNames;
import scala.concurrent.forkjoin.ThreadLocalRandom;

object GBIPUIDevFTPServices {
  
  val csvFileName:String = "BulkJobUodateSimpleTest.csv";  
  val domainName:String = ".nike.com";
  val nikeAuthToken:String = "eyJraWQiOiJ0b2tlbktleSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJOaWtlIEdCSVAiLCJhdWQiOiJOaWtlIEdCSVAgVXNlcnMiLCJleHAiOjE0NjI5OTg0MjIsImp0aSI6IlFLZUJYVDc0Uzc2QTQyRG5ITXYyV2ciLCJpYXQiOjE0NjI5OTEyMjIsIm5iZiI6MTQ2Mjk5MTEwMiwic3ViIjoiYWRtaW4iLCJHcm91cHMiOlsiQXBwbGljYXRpb24uQ0RULkRldk9wcy5HQklQLkFydEJ1eWVyIiwiQXBwbGljYXRpb24uQ0RULkRldk9wcy5HQklQLkRpZ2lUZWNoIiwiQXBwbGljYXRpb24uQ0RULkRldk9wcy5HQklQLkltYWdlRWRpdG9yIiwiQXBwbGljYXRpb24uQ0RULkRldk9wcy5HQklQLk1lcmNoT3BzIiwiQXBwbGljYXRpb24uQ0RULkRldk9wcy5HQklQLlBob3RvZ3JhcGhlciIsIkFwcGxpY2F0aW9uLkNEVC5EZXZPcHMuR0JJUC5TdHVkaW9PcHMiLCJBcHBsaWNhdGlvbi5DRFQuRGV2T3BzLkdCSVAuU3R1ZGlvU3R5bGlzdCIsIkFwcGxpY2F0aW9uLkNEVC5EZXZPcHMuR0JJUC5TdXBlcnVzZXIiLCJBcHBsaWNhdGlvbi5FWFRVU1JNR1JVSS5HQklQLkFydEJ1eWVyIiwiQXBwbGljYXRpb24uRVhUVVNSTUdSVUkuR0JJUC5EaWdpVGVjaCIsIkFwcGxpY2F0aW9uLkVYVFVTUk1HUlVJLkdCSVAuSW1hZ2VFZGl0b3IiLCJBcHBsaWNhdGlvbi5FWFRVU1JNR1JVSS5HQklQLk1lcmNoT3BzIiwiQXBwbGljYXRpb24uRVhUVVNSTUdSVUkuR0JJUC5QaG90b2dyYXBoZXIiLCJBcHBsaWNhdGlvbi5FWFRVU1JNR1JVSS5HQklQLlN0dWRpb09wcyIsIkFwcGxpY2F0aW9uLkVYVFVTUk1HUlVJLkdCSVAuU3R1ZGlvU3R5bGlzdCIsIkFwcGxpY2F0aW9uLkVYVFVTUk1HUlVJLkdCSVAuU3VwZXJ1c2VyIiwiYWRtaW5pc3RyYXRvcnMiXX0.GxxPRt6y2pBgHswg6NSHl3z-fVKQtbnlVQ-P67UFD0aeArmhSUW9M8TBqSdAIEjRQ5_bsEHYU0L3q34G3ukBcRjhR93c5h4n9vCdRhaBTzIGOm0SPHfHGWXJGaCA49oznxwheSiN0_Cz2HbfwSkdlLkD0aTZMlkuMYuRwaLGHh7ro-xIujjRdQDFiWYsZ3W8H5lfsGxA1Zc_I02weabyicAOcjDlbtFVjkgLph-9Ib8xilVX9_qF2ZPrpr6tjVOe-q4XEA7XQHkGea-W2fQGhcFXqV4NGkUX34PM8iHLrW7tyj_iaqgB8uD9-aMf4nlt7cs1YLEF3iVMHPzNsnn0cQ";
  val hostLoc="gbipapiuat.sandbox.dbt.svs.nike.com"
  
   
  val getGeneratePassword = exec(
    http("Get History")
      .get("http://"+hostLoc+":80/api/account/generate")
      .check(status.in(200 to 210),jsonPath("$.plaintextPassword").saveAs("plaintextPassword")))
}